#!/usr/bin/env bash

script_folder=$(dirname $0)
# source ${script_folder}/naming
source config

prefix="lunenu"
name_folder() {
    echo "${prefix}_$1_$2_$3";
}

V=(100 150 200 250 300 350 400 450 500)
prog="t-final-local-search-init-redundant-random-sbx4-local-search-mut-pc0.7-pm0.2"
solver="$prog-$version.jar"

for v in "${V[@]}"; do
    echo "[Running] $prefix $v"
    for r in "${R[@]}"; do
        echo $(name_folder $v $1 $r) 
        echo $pc 
        echo $pm
    done | parallel -N3 java -cp target/${solver} hust.mso.ga.Main {1} {2} {3} ${cache_dir}
    # done | parallel -N3 echo {1} {2} {3}
done
